//
// Created by 28636 on 2025/5/26.
//

#ifndef PLANTSVSZOMBIES_ANDROIDTV_KEYCODES_H
#define PLANTSVSZOMBIES_ANDROIDTV_KEYCODES_H

namespace Sexy {

enum KeyCode {
    KEYCODE_INVALID = -1,
    KEYCODE_ACCEPT = 13,
    KEYCODE_ESCAPE = 27,
    KEYCODE_ESCAPE2 = 305,
    KEYCODE_LEFT = 37,
    KEYCODE_UP = 38,
    KEYCODE_RIGHT = 39,
    KEYCODE_DOWN = 40,
    KEYCODE_SHOVEL = 49,
    KEYCODE_HAMMER = 50,
};

}

#endif // PLANTSVSZOMBIES_ANDROIDTV_KEYCODES_H
